const GET_TOURS_BEGIN = "GET_TOURS_BEGIN";
const GET_TOURS_SUCCESS = "GET_TOURS_SUCCESS";
const GET_TOURS_ERROR = "GET_TOUR_SUCCESS";
const REMOVE_TOUR = "REMOVE_TOUR";

export { GET_TOURS_BEGIN, GET_TOURS_SUCCESS, GET_TOURS_ERROR, REMOVE_TOUR };
